# Generated by Django 4.1.3 on 2022-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='ddlj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
